/** Mapping of RPC codes to HTTP status values. */
export const RPC_CODES = {
  RPC_OK: 200,
  RPC_CREATED: 201,

  RPC_BAD_REQUEST: 400,
  RPC_UNAUTHORIZED: 401,
  RPC_FORBIDDEN: 403,
  RPC_NOT_FOUND: 404,
  RPC_METHOD_NOT_ALLOWED: 405,
  RPC_TIMEOUT: 408,
  RPC_CONFLICT: 409,
  RPC_PRECONDITION_FAILED: 412,
  RPC_PAYLOAD_TOO_LARGE: 413,
  RPC_UNSUPPORTED_MEDIA_TYPE: 415,
  RPC_TOO_MANY_REQUESTS: 429,

  RPC_INTERNAL_SERVER_ERROR: 500,
  RPC_NOT_IMPLEMENTED: 501,
  RPC_BAD_GATEWAY: 502,
  RPC_SERVICE_UNAVAILABLE: 503,
  RPC_GATEWAY_TIMEOUT: 504,

  RPC_PARSE_ERROR: 460,
  RPC_VALIDATION_ERROR: 461,
  RPC_PROCEDURE_NOT_FOUND: 462,
  RPC_CONTEXT_ERROR: 463,
  RPC_MIDDLEWARE_ERROR: 464,
  RPC_SERIALIZATION_ERROR: 465,
} as const

/** Template shape for custom RPC code strings. */
type RPCCodeShape = `RPC_${Uppercase<string>}` & {}
/** Union of built-in RPC codes and custom code strings. */
export type RPCCode = keyof typeof RPC_CODES | RPCCodeShape
